# Generated by Django 2.1.7 on 2019-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190319_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
