# Generated by Django 2.1.7 on 2019-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190319_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
